# Generated by Django 4.0.4 on 2022-06-04 07:10

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('backend', '0003_company'),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img', models.ImageField(blank=True, default='defaultProfile.png', null=True, upload_to='photos%d%y%m')),
                ('description', models.TextField(blank=True, max_length=200, null=True)),
                ('expone', models.CharField(blank=True, max_length=100, null=True)),
                ('exptwo', models.CharField(blank=True, max_length=100, null=True)),
                ('expthree', models.CharField(blank=True, max_length=100, null=True)),
                ('degone', models.ImageField(blank=True, default='defaultProfile.png', null=True, upload_to='photos%d%y%m')),
                ('degtwo', models.ImageField(blank=True, default='defaultProfile.png', null=True, upload_to='photos%d%y%m')),
                ('degthree', models.ImageField(blank=True, default='defaultProfile.png', null=True, upload_to='photos%d%y%m')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
