# Generated by Django 4.0.4 on 2022-06-11 07:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0007_alter_profile_joined_alter_profile_numbercontact'),
    ]

    operations = [
        migrations.RenameField(
            model_name='company',
            old_name='name',
            new_name='companyname',
        ),
        migrations.RenameField(
            model_name='company',
            old_name='email',
            new_name='emailcontact',
        ),
        migrations.RenameField(
            model_name='company',
            old_name='title',
            new_name='jobname',
        ),
        migrations.AddField(
            model_name='company',
            name='deactive',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='company',
            name='endin',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='company',
            name='numbercontact',
            field=models.BigIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='company',
            name='startin',
            field=models.DateField(blank=True, null=True),
        ),
    ]
