# Generated by Django 4.0.4 on 2022-06-14 06:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0009_alter_company_image_alter_profile_degone_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='degone',
            field=models.ImageField(blank=True, default='def-img.png', null=True, upload_to='photos%d%y%m'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='degthree',
            field=models.ImageField(blank=True, default='def-img.png', null=True, upload_to='photos%d%y%m'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='degtwo',
            field=models.ImageField(blank=True, default='def-img.png', null=True, upload_to='photos%d%y%m'),
        ),
    ]
