# Generated by Django 4.0.4 on 2022-06-17 08:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0010_alter_profile_degone_alter_profile_degthree_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='backProf',
            field=models.ImageField(blank=True, default='def-profile.png', null=True, upload_to='photos%d%y%m'),
        ),
    ]
