# Generated by Django 4.0.4 on 2022-07-02 07:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0012_remove_company_owner_company_category_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='company',
            old_name='created_at',
            new_name='created',
        ),
    ]
